### PR TITLE
Allow localhost cors in development

### LINKED ISSUE #47: Allow localhost origin in development mode (CORS)
The current CORS configuration makes local testing a pain. We should have some sort of flag which removes CORS when we are doing local development.

### PR DESCRIPTION
**Pull request by maxwofford**
Closes #47

### CODE REVIEW

**Comment by zachlatta** [comment]
Should a test be added with this PR? Existing CORS functionality is tested.

**Comment by paked** [comment]
What's the status on testing here?

**Comment by MaxWofford** [comment]
@paked Need to look into the best way to test this with rspec.

**Comment by paked** [comment]
I'm in favour here of merging this PR and creating an issue for testing CORS which we can address later.

**Comment by zachlatta** [comment]
Just made some changes to allow testing and added tests for this 🙌.

Also rebased changes on top of master to get rid of those security warnings from Hakiri. Should be ready to merge!

**Pull request merged**
