### PR TITLE
Check-in deadlines include a time of day

### PR DESCRIPTION
**Pull request by maxwofford**
For example "This check-in closes on Monday morning"

### CODE REVIEW

**Comment by MaxWofford** [comment]
Working on the tests right now, I'll ping you @paked when it's good to go!

**Review by paked — COMMENTED** [review]
Other than rubocop being mad, this looks pretty good!

**Comment by paked** [comment]
Thanks!

**Comment by MaxWofford** [comment]
@paked Comments addressed!

**Pull request merged**
